work_dir: ./s2stgcn/recognition/ntu-xsub/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/FPHA/handfast_preprocessed/train_data3_1.npy
  label_path: ./data/FPHA/handfast_preprocessed/train_label3_1.pkl


test_feeder_args:
  data_path: ./data/FPHA/handfast_preprocessed/val_data3_1.npy
  label_path: ./data/FPHA/handfast_preprocessed/val_label3_1.pkl



# models
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 45
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'fasthand'
    strategy: 'spatial'

#optim
weight_decay: 0.001
base_lr: 0.01
step: [10, 50]

# training
device: [0]
batch_size: 4
test_batch_size: 4
num_epoch: 800
